aplicacion/urls.py
from django import urls
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('app.urls')),
    path('admin/', admin.site.urls),
]

app/urls.py
from django.urls import path 
from . import views 

app_name = 'app' 
urlpatterns = [
    path('', views.index, name='index'), 
    path('', views.index, name='inicio'), 
    # login
    path('login/',views.iniciar_sesion_view, name='iniciar_sesion_view'),
    path('post_login',views.iniciar_sesion_post, name= 'iniciar_sesion_post'),
    # loout
    path('logout/',views.cerrar_sesion, name='cerrar_sesion'),
    # crear cuenta
    path('registro/',views.form_registro_view, name='form_registro_view'),
    path('registro_post/', views.registro_post, name='registro_post'),

# NUESTRO PROYECTOOOO

    path('cuenta',views.cuenta_view, name='cuenta_view'),
    path('cuenta_post/', views.cuenta_post, name='cuenta_post'),
    path('index',views.index_view, name='index_view'),
    path('index_post',views.index_post, name= 'index_post'),
    
    path('inicio',views.inicio_view, name='inicio_view'),
    path('inicioAdmin',views.inicioAdmin, name='inicioAdmin'),

    path('afiliacion',views.afiliacion_view, name='afiliacion_view'),
    path('aprobarAfiliacion',views.aprobarAfiliacion_view, name='aprobarAfiliacion_view'),
    path('aprobarIndividuo',views.aprobarIndividuo_view, name='aprobarIndividuo_view'),
    
    path('configure',views.configure_view, name='configure_view'),
    path('configure_post',views.configure_post, name='configure_post'),



    
  
    path('consultaLista',views.consultaLista_view, name='consultaLista_view'),
    path('consultaParti',views.consultaParti_view, name='consultaParti_view'),
    
    
    path('implicar',views.implicar_view, name='implicar_view'),
    

    # path('peliculas', views.peliculas_view, name='peliculas'),
    # path('peliculas/crear',views.form_crear_pelicula_view, name='form_crear_pelicula_view'),
    # path('peliculas/crear_post',views.crear_pelicula_post, name='crear_pelicula_post'),
    path('consultaLista',views.consultaLista_view, name='consultaLista_view'),
    path('consultaLista/<int:id>',views.consultALista_view, name='consultALista_view'),


    path('politico',views.politico_view, name='politico'),
    path('politico/crear',views.form_crear_politico_view, name='form_crear_politico_view'),
    path('politico/crear_post/', views.crear_politico_post, name='crear_politico_post'),
    
    path('habilitar',views.habilitar_view, name='habilitar_view'),
    path('habilitar/<int:id>',views.Habilitarr_view, name='Habilitarr_view'),
    path('habilitar_post',views.habilitar_post, name='habilitar_post'),

    path('aprobarProceso',views.aprobarProceso_view, name='aprobarProceso_view'),
    path('aprobarProceso/<int:id>',views.aprobarProcesoo_view, name='aprobarProcesoo_view'),
    path('aprobarProceso_post',views.aprobarProceso_post, name='aprobarProceso_post'),

    # path('consultaIndis',views.consultaIndis_view, name='consultaIndis_view'),
    path('consultaIndi',views.consultaIndi_view, name='consultaIndi_view'),
    path('consultaIndi/<int:id>',views.consultAIndi_view, name='consultAIndi_view'),
    path('aprobar_indivi_post',views.aprobar_indivi_post, name='aprobar_indivi_post'),
    
    path('individuo',views.individuo_view, name='individuo'),
    path('individuo/crear',views.form_crear_individuo_view, name='form_crear_individuo_view'),
    path('individuo/crear_post/',views.crear_individuo_post, name='crear_individuo_post'),

    path('consultaProce',views.consultaProce_view, name='consultaProce_view'),
    path('proceso',views.proceso_view, name='proceso_view'),
    path('proceso/crear',views.form_crear_proceso_view, name='form_crear_proceso_view'),
    path('proceso/crear_post/',views.crear_proceso_post, name='crear_proceso_post'),



    path('nosotros',views.nosotros_view, name='nosotros_view'),



]

 

nubecita/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("app.urls")),

]

app/templates/app/Habilitarr.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>miprimera pagina web

    </title>
    <link rel="stylesheet" href="css/habilitar.css">
<!-- link para fond awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href='https://fonts.googleapis.com/css?family=Ubuntu:500' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'app/habilitar.css' %}">



</head>

<body>
    

    <div class="inicio">
      <div class="inicio-header">
        <h1><img src="{% static 'app/titulomermelada.jpg' %}" alt="no hay imagen"></h1>
        <h1>Habiliar/Deshabilitar Ciudadano</h1>
      </div>
      <div class="inicio-form">
        
        <table border="1">
          <thead>
              <tr>
                  <th>Username</th>
                  <th>Nombres</th>

                  <th>Aprobado/No aprovado</th>
              </tr>
          </thead>
          <tbody>
      
              
              
              <tr>
                  <td>{{info.username}}</td>
                  <td>{{info.first_name}}</td>

              
                  <td>{% if info.is_active %}
                      activado
                      {% else %}
                      no esta activado
                      {% endif %}
              
          </tbody>
      </table>

       
        <p>
          <form method="post" action="{% url 'app:habilitar_post' %}" >
            {% csrf_token %} 
            <br>
            <input type="text" name="id" id="id" style="display: none;" value="{{info.id}}">
            <br>
            <input type="submit" value="aprobar" class="login-button">
            <br>
          </form>
  
        </p>  
        
        
        <a href="{% url 'app:inicioAdmin' %}" >
            <input type="button" value="Cancel" class="login-button" > 
            </a>
            <br>
        </p>    



      </div>
    </div>
    
</body>

</html>

app/templates/app/afiliacion.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>miprimera pagina web

    </title>
    <link rel="stylesheet" href="css/afiliacion.css">
<!-- link para fondo awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href='https://fonts.googleapis.com/css?family=Ubuntu:500' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'app/afiliacion.css' %}">

</head>

<body>
    

    <div class="afiliacion">
      <div class="afili-header">
        <h1><img src="ima/titulomermelada.jpg" alt="no hay imagen"></h1>
        <h1>Afiliacion de un individuo a un Partido Politico</h1><br>
      </div>
      <div class="afili-form">

        
        <table border="1">
            <thead>
                <tr>
                    <th>Username</th>
                    <th>Activado/Desactivado</th>
                </tr>
            </thead>
            <tbody>
        
                {% for p in usuarios %}
                
                <tr>
                    
                    <td><a href="{% url 'app:consultAIndi_view' p.id%}">{{p.username}}</a></td>
  
                
                    <td>{% if p.is_activate %}
                        esta activo
                        {% else %}
                        esta desactivado
                        {% endif %}
                {% endfor %}
            </tbody>
          </table>
       
        
        <br>
        {% if request.user.is_superuser %}
          <a href="{% url 'app:inicioAdmin' %}" >
          <input type="button" value="Cancel" class="login-button">
        {% else %}
	        
          <a href="{% url 'app:inicio_view' %}" >
          <input type="button" value="Cancel" class="login-button">
        {% endif %}
        <br>
       

        </div>
    </div>
    
</body>

</html>

app/templates/app/aprobar-afiliacion.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>miprimera pagina web

    </title>
    <link rel="stylesheet" href="css/aprobar-afiliacion.css">
<!-- link para fond awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href='https://fonts.googleapis.com/css?family=Ubuntu:500' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'app/aprobar-afiliacion.css' %}">
    
</head>

<body>
    

    <div class="inicio">
      <div class="inicio-header">
        <h1><img src="{% static 'app/titulomermelada.jpg' %}" alt="no hay imagen"></h1>
        <h1>APROBAR AFILIACION INDIVIDUO</h1>
      </div>
      <div class="inicio-form">
       
        <table border="1">
          <thead>
              <tr>
                  <th>Username</th>
                  <th>Activado/Desactivado</th>
              </tr>
          </thead>
          <tbody>
      
              {% for p in usuarios %}
              
              <tr>
                  
                  <td><a href="{% url 'app:consultAIndi_view' p.id%}">{{p.username}}</a></td>

              
                  <td>{% if p.is_activate %}
                      esta activo
                      {% else %}
                      esta desactivado
                      {% endif %}
              {% endfor %}
          </tbody>
        </table>




       
        <p>
          <a href="{% url 'app:inicioAdmin' %}" >
            <input type="button" value="Approve" class="login-button" > 
            </a>
            <br>
            <br><a href="{% url 'app:inicioAdmin' %}" >
            <input type="button" value="Reject" class="login-button" > 
            </a>
        <br>
        <br>
        {% if request.user.is_superuser %}
          <a href="{% url 'app:inicioAdmin' %}" >
          <input type="button" value="Cancel" class="login-button">
        {% else %}
	        
          <a href="{% url 'app:inicio_view' %}" >
          <input type="button" value="Cancel" class="login-button">
        {% endif %}
        <br>
        </p>    



      </div>
    </div>
    
</body>

</html>

app/templates/app/aprobar-proceso.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>miprimera pagina web

    </title>
    <link rel="stylesheet" href="css/aprobar-proceso.css">
<!-- link para fond awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href='https://fonts.googleapis.com/css?family=Ubuntu:500' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'app/aprobar-proceso.css' %}">

</head>

<body>
    

    <div class="inicio">
      <div class="inicio-header">
        <h1><img src="{% static 'app/titulomermelada.jpg' %}" alt="no hay imagen"></h1>
        <h1>APROBAR PROCESO</h1>
      </div>
      <div class="inicio-form">
        
        <table border="1">
          <thead>
              <tr>
                  <th>Proceso</th>
                  <th>Aprobar/desaprobar</th>
              </tr>
          </thead>
          <tbody>
      
              {% for p in usuarios %}
              
              <tr>
                  
                  <td><a href="{% url 'app:aprobarProcesoo_view' p.id%}">{{p.titulo}}</a></td>

              
                  <td>{% if p.aprobado %}
                      esta activado
                      {% else %}
                      esta desactivado
                      {% endif %}
              {% endfor %}
          </tbody>
        </table>










            <br>
            
        </p>  
        
        <br>
        <a href="{% url 'app:inicioAdmin' %}" >
            <input type="button" value="Cancel" class="login-button" > 
            </a>
            <br>
        </p>   



      </div>
    </div>
    
</body>

</html>

app/templates/app/categoria.html
{% extends 'app/base.html' %}



{% block titulo %}
peliculas
{% endblock %}

{% block contenido %}
<a href="{% url 'app:peliculas' %}">ir a pagina de pliculas</a>
    <br>
    <a href="{% url 'app:index' %}">ir al inicio</a>
    <h1>categoria</h1>

    <p>el nombre del actor es {{actor}} y la edad es {{edad}}</p>

    {% if jubilado %}
    <p>el actor  es jubilado </p>
    {% else %}
    <p>el actor aun trrabaja</p>
    {% endif %}


    <h2>filmografia del ator</h2>

    <ul>
        {% for  pelicula in filmografia %}

        <li>{{pelicula.titulo}}</li>

        {% endfor %}

    </ul>


    <h2>tablas de pelicula actor</h2>

    <table border="1">

        <thead> 
            <tr>
                    <th>titulo</th>
                    <th>año</th>
            </tr>

        </thead>
        <tbody>
            {% for movie in filmografia %}
            <tr>
                <td>
                    {{movie.titulo}}
                </td>  
                <td>
                    {{movie.year}}
                </td>

            </tr>
            {% endfor %}
        </tbody>


    </table>




{% endblock %}

app/templates/app/consultAIndi_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>miprimera pagina web

    </title>
    <link rel="stylesheet" href="css/consulta-indi.css">
<!-- link para fond awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href='https://fonts.googleapis.com/css?family=Ubuntu:500' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'app/consulta-indi.css' %}">

</head>

<body>
    

    <div class="login">
      <div class="login-header">
        
        <h1>Aprobar Individuos</h1>
      </div>
      <div class="login-form">
     
       
        <table border="1">
            <thead>
                <tr>
                    <th>Apellidos</th>
                    <th>Nombres</th>

                    <th>Aprobado/No aprovado</th>
                </tr>
            </thead>
            <tbody>
        
                
                
                <tr>
                    <td>{{info.apellidos}}</td>
                    <td>{{info.nombres}}</td>

                
                    <td>{% if info.aprobado %}
                         aprobado
                        {% else %}
                        no esta aprobado
                        {% endif %}
                
            </tbody>
        </table>
        <p>
          
           
           
           
        
           
            <!-- <select name="enviar mensaje" size="3">
                {% for p in individuos %}
                    <option label="{{p.apellidos}}">{{p.id}}</option>

                {% endfor %}
            </select> -->
        
          </p>
          <form method="post" action="{% url 'app:aprobar_indivi_post' %}" >
            {% csrf_token %} 
            <br>
            <input type="text" name="id" id="id" style="display: none;" value="{{info.id}}">
            <br>
            <input type="submit" value="aprobar" class="login-button">
            <br>
          </form>

          
            {% if request.user.is_superuser %}
              <a href="{% url 'app:inicioAdmin' %}" >
              <input type="button" value="Cancel" class="login-button">
            {% else %}
                
              <a href="{% url 'app:inicio_view' %}" >
              <input type="button" value="Cancel" class="login-button">
            {% endif %}
            <br>
           
      </div>
    </div>
    
</body>

</html>

app/templates/app/cuenta2.html
{% extends 'app/cuenta.html' %}




  {% block contenido %}
<form action="{% url 'app:cuenta_post' %}" method="POST">
    {% csrf_token %} 

    </ul>
        

    <div class="login">
      <div class="login-header">
      
        <h1>Registro</h1>
      </div>
      <div class="login-form">
        <h3>Username:</h3>
        <input type="text" name="username" placeholder="Username"/><br>
        <h3>Password:</h3>
        <input type="password" name="password" placeholder="Password"/>
        <h3>Email</h3>
        <input type="email" name="email" placeholder="Email">
        <h3>Name</h3>
        <input type="text" name="name" placeholder="First Name">
        <h3>Last Name</h3>
        <input type="text" name="last_name" placeholder="Last name">
        <br>
        <a href="index.html" >
          <input type="submit"  value="Create" class="login-button">
        </a><br>
        <br>
        <a href="{% url 'app:index_view' %}">Iniciar sesión</a>
        <br>

      
      </div>
    </div>
</form> 
  {% endblock %}

app/templates/app/errorLogin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error de inicio de sesion</title>
    <link rel="stylesheet" href="{% static 'app/inicio.css' %}">

</head>
<body>
    <div class="inicio-header">
        <h1> <img src="{% static 'app/titulomermelada.jpg' %}" alt="no hay imagen"></h1>
    </div>
    <h1>error de autenticacion </h1>
    <a href="{% url 'app:index_view' %}">volver</a>
  
</body>
</html>

app/templates/app/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>miprimera pagina web

    </title>
    <!-- <link rel="stylesheet" href="css/index.css"> -->
<!-- link para fond awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href='https://fonts.googleapis.com/css?family=Ubuntu:500' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'app/index.css' %}"> 

</head>

<body>

  <form action="{% url 'app:index_post' %}" method="POST">
    {% csrf_token %} 
    <main>
      {% block contenido %}
          <div class="login">
            <div class="login-header">
              <h1><img src="{% static 'app/titulomermelada.jpg' %}" alt="no hay imagen"></h1>
              <h1>Login</h1>
            </div>
            <div class="login-form">
              <h3>Username:</h3>
              <input type="text" name="username" placeholder="Username"/><br>
              <h3>Password:</h3>
              <input type="password" name="password" placeholder="Password"/>
              <br>
              <a href="inicio.html">
              <br>
              <input type="submit"  value="iniciar sesión" class="login-button"/>
              <br>
              <br>
              <a href="{% url 'app:cuenta_view' %}">Crear cuenta</a>
              <br>
              <br>
              <h6 class="no-access">Can't access your account?</h6>
              <br>

            </div>
          </div>
      {% endblock %}

    </main>
  </form> 
    
</body>

</html>

app/templates/app/inicio-user.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>miprimera pagina web

    </title>
    <!-- <link rel="stylesheet" href="css/inicio.css"> -->


    
<!-- link para fond awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href='https://fonts.googleapis.com/css?family=Ubuntu:500' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'app/inicio.css' %}"> 

</head>

<body>


  <main>
    {% block contenido %}
    <!-- {% if request.user.is_authenticated %} -->

      <ul id="nav">
        <a href="{% url 'app:inicio_view' %}">
          <li > Inicio</li>
        </a>
        <a href="{% url 'app:index_view' %}">
          

          <li > cerrar sesion</li>
        </a>
        <a href="{% url 'app:nosotros_view' %}">
          <li > Nosotros</li>
        </a>
        <a href="{% url 'app:configure_view' %}">
          <li > Configuración</li>
        </a>
      
      </ul>

        <div class="inicio">
          <div>
            <H1>Bienvenido {{ request.user.first_name }}</H1>
          </div>
          <div class="inicio-header">
            <h1> <img src="{% static 'app/titulomermelada.jpg' %}" alt="no hay imagen"></h1>
          </div>
          <div class="inicio-form">
            <br>
            <a href="{% url 'app:form_crear_politico_view' %}">
            <input type="button" value="Crear Partido Politico"/>
            </a>
            <br>
            <a href="{% url 'app:consultaLista_view' %}">
            <input type="button" value="Lista partidos politicos"/>
            </a>
            <br>
           
            
            <a href="{% url 'app:form_crear_individuo_view' %}">
            <input type="button" value="Crear individuo">
            </a>

            <br>
            <a href="{% url 'app:consultaIndi_view' %}">
            <input type="button" value="Lista de individuos">
            </a>
            <br>
            <a href="{% url 'app:consultaIndi_view' %}">
            <input type="button" value="Consutar individuo">
            </a>
            <br>
            <!-- <a href="{% url 'app:afiliacion_view' %}">
            <input type="button" value="Afiliacion individuo a Partido">
            </a>

            <br> -->
            <a href="{% url 'app:proceso_view' %}">
            <input type="button" value="Crear proceso">

            <br>
            <a href="{% url 'app:implicar_view' %}">
            <input type="button" value="Implicar afiliado en un proceso">
            </a>
            <br>
            <a href="{% url 'app:consultaProce_view' %}">
            <input type="button" value="Consutar proceso">
            </a>

            <br>

          </div>
        </div>
        <!-- {% else %}
      
          <a href="{% url 'app:iniciar_sesion_view' %}">iniciar sesion</a>
          <br>
          <span> El usuario no esta autenticado</span>
          <br>
          <a href="{% url 'app:form_registro_view' %}">crear cuenta</a>
      
          {% endif %} -->



    {% endblock %}
  </main>
</body>

</html>

app/templates/app/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ingresar</title>
    <style>
        body{
            display: grid;
            place-items: center;
        }
        fieldset{
            border: 0;
            outline: none;

        }
    </style>

</head>
<body>

    <form action="{% url 'app:iniciar_sesion_post' %}" method="POST">
        {% csrf_token %}

        <fieldset>
            <label >Username</label>
            <input type="text" name="username">
        </fieldset>
        <fieldset>
            <label >Password</label>
            <input type='password'" name="password">
        </fieldset>
        <fieldset>
            <button type="submit">iniciar sesión</button>
        </fieldset>
    </form>



</body>
</html>

app/templates/app/proceso.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>miprimera pagina web

    </title>
    <link rel="stylesheet" href="css/proceso.css">
<!-- link para fond awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href='https://fonts.googleapis.com/css?family=Ubuntu:500' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'app/proceso.css' %}">



</head>

<body>
  <form action="{% url 'app:crear_proceso_post' %}" method="POST">    
    {% csrf_token %}
    <div class="inicio">
      <div class="inicio-header">
        
        <h1>CREAR PROCESO</h1>
      </div>
      <div class="inicio-form">

        <P>Titulo: <input type="text" name="titulo" placeholder="Titulo"/><br></P> 
        
        <P>Fecha de inicio:  <input type="date" name="fecha_inicio"><br></P> 
       
        <P>Fecha de finalización:    <input type="date" name="fecha_fin"><br></P> 
        
       

        <P>Entidad: <input type="text" name="entidad" placeholder="Entidad"/><br></P>

        <P>Monto: <input type="number" name="monto" placeholder="Monto"/><br></P>

        <P>Comentarios: <input type="text" name="comentarios" placeholder="Comentarios"/><br></P>
        
        
        <p id="anuncio">El proceso deberá ser aprobado por el<span id="rojo">administrador</span> . </p>
        <p>
        
        <button type="submit">crear proceso</button>

        <br>
        
        <br>
        <br>
        {% if request.user.is_superuser %}
          <a href="{% url 'app:inicioAdmin' %}" >
          <input type="button" value="Cancel" class="login-button">
        {% else %}
	        
          <a href="{% url 'app:inicio_view' %}" >
          <input type="button" value="Cancel" class="login-button">
        {% endif %}
        <br>
            <br>
        </p>    



      </div>
    </div>
  </form>     
</body>

</html>

app/templates/app/registro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro</title>
    <style>
        body{
            display: grid;
            place-items: center;
        }
        fieldset{
            border: 0;
            outline: none;

        }
    </style>

</head>
<body>
    
    <h1>ingreso </h1>
    <form action="{% url 'app:registro_post' %}" method="POST">
   
    {% csrf_token %}
    <fieldset>
        <label >Nombres</label>
        <input type="text" name="nombres">
    </fieldset>
    <fieldset>
        <label >Apellidos</label>
        <input type="text" name="apellidos">
    </fieldset>
    <fieldset>
        <label >Username</label>
        <input type="text" name="username">
    </fieldset>
    <fieldset>
        <label >Password</label>
        <input type="password" name="password">
    </fieldset>
    <fieldset>
        <button type="submit">iaaaaaaaaaaaaaa</button>
    </fieldset>
    </form>
</body>
</html>